from .board import Board

def start_game():
    print("Generating solved board...")
    board = Board(3, False)
    board.display()
    print("Solvability: " + str(board.is_solvable()))
    print("Blank is at: " + str(board.find_blank()))
    print("Legal moves: " + str(board.legal_moves()))
    print("Is solved: " + str(board.is_solved()))
    print("Shuffling...")
    board.shuffle()
    board.display()
    print("Solvability: " + str(board.is_solvable()))
    print("Blank is at: " + str(board.find_blank()))
    print("Legal moves: " + str(board.legal_moves()))
    print("Is solved: " + str(board.is_solved()))
    print()
    print("Generating shuffled board...")
    board2 = Board(3, True)
    board2.display()
    print("Solvability: " + str(board2.is_solvable()))
    print("Blank is at: " + str(board2.find_blank()))
    print("Legal moves: " + str(board2.legal_moves()))
    print("Is solved: " + str(board2.is_solved()))
    print("Tring move U...")
    board2.do_move("U")
    board2.display()
    print("Is solved: " + str(board2.is_solved()))
